In [2]:
import plotly.express as px
import pandas as pd

In [3]:
df = pd.read_csv("data-sample.csv")

In [4]:
df

,Unnamed: 0,frequency,period_ending,ship_type,ship_size,port_name,port_country,region_corridor,metric,draft,ship_count,dwt,modified_dwt,avg_time_spent_mins,year
0,0,MONTHLY,2018-01-31,BULKER,MEDIUM,Durban,South Africa,Africa,Entries,EMPTY,25,1518305,0,NaN,2018
1,1,MONTHLY,2018-01-31,BULKER,SMALL,Abidjan,Cote D'ivoire,Africa,Entries,EMPTY,4,123016,0,NaN,2018
2,2,MONTHLY,2018-01-31,BULKER,MEDIUM,Arzew El-Djedid,Algeria,Africa,Entries,EMPTY,3,166488,0,NaN,2018
3,3,MONTHLY,2018-01-31,BULKER,SMALL,Moma,Mozambique,Africa,Entries,EMPTY,1,28392,0,NaN,2018
4,4,MONTHLY,2018-01-31,BULKER,SMALL,Lagos (Nigeria),Nigeria,Africa,Entries,EMPTY,3,107440,0,NaN,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228768,228768,MONTHLY,2018-12-31,TANKER,SMALL,River Plate Uruguayan Lightering Areas,Uruguay,South America,Exits,PARTIAL,13,325859,32168,1564.028154,2018
228769,228769,MONTHLY,2018-12-31,TANKER,MEDIUM,Quintero,Chile,South America,Exits,PARTIAL,2,105818,8849,8483.933500,2018
228770,228770,MONTHLY,2018-12-31,TANKER,SMALL,Rosario,Argentina,South America,Exits,PARTIAL,1,46992,8458,2157.617000,2018
228771,228771,MONTHLY,2018-12-31,TANKER,SMALL,Acu Superport,Brazil,South America,Exits,PARTIAL,1,37606,6396,17442.817000,2018
228772,228772,MONTHLY,2018-12-31,TANKER,SMALL,Mamonal,Colombia,South America,Exits,PARTIAL,12,182341,27973,1456.290333,2018